updateDocsComment: "Thanks for the pull request! If you are making any changes to the user-facing functionality, please be sure to update the documentation in the `README` or `docs/` folder alongside your change. :heart:"


requestInfoReplyComment: Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?
requestInfoLabelToAdd: more-information-needed


newPRWelcomeComment: Welcome! Congrats on your first pull request to the Architect theme. If you haven't already, please be sure to check out [the contributing guidelines](https://github.com/pages-themes/architect/blob/master/docs/CONTRIBUTING.md).


firstPRMergeComment: "Congrats on getting your first pull request to the Architect theme merged! Without amazing humans like you submitting pull requests, we couldn’t run this project. You rock! :tada:<br /><br />If you're interested in tackling another bug or feature, take a look at [the open issues](https://github.com/pages-themes/architect/issues), especially those [labeled `help wanted`](https://github.com/pages-themes/architect/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)."
